# Generated by Django 4.0.3 on 2024-07-02 03:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('cmdbid', models.CharField(max_length=15, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^CMDB[0-9]{11}', 'invalid CMDB ID')])),
                ('name', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=150, null=True)),
                ('manufacturer', models.CharField(max_length=50, null=True)),
                ('site', models.CharField(max_length=50, null=True)),
                ('area', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=30, null=True)),
                ('usage_type', models.CharField(max_length=30, null=True)),
                ('urgency', models.CharField(max_length=30, null=True)),
                ('primary_function', models.CharField(max_length=30, null=True)),
                ('monitored', models.CharField(max_length=30, null=True)),
                ('sox_relevance', models.CharField(max_length=50, null=True)),
                ('dns', models.CharField(max_length=30, null=True)),
                ('domain', models.CharField(max_length=30, null=True)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('owner', models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator('^IF[0-9]{8}', 'invalid Global ID')])),
                ('last_seen', models.DateTimeField(null=True)),
                ('modified_at', models.DateTimeField()),
                ('modified_by', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'repo_host',
            },
        ),
    ]
